---

- name: add Prometheus user 
  user:
    name: prometheus
    state: present
    shell: /sbin/nologin

- name: Create prometheus folder
  file:
    path: '{{ conf_prom_folder }}'
    owner: prometheus
    group: prometheus
    mode: '0644'
    state:  directory


- name: Create prometheus folder
  file:
    path: '{{ var_prom_folder }}'
    owner: prometheus
    group: prometheus
    mode: '0644'
    state:  directory


- name: Get the package from Prometheus
  get_url: 
    url: '{{ prom_url }}'
    dest: /tmp/'{{ prom_name }}'.tar.gz

- name: untar prometheus Package
  unarchive:
    src: /tmp/'{{ prom_name }}'.tar.gz
    dest: /tmp/
    remote_src: yes
    list_files: yes
  register: archive_contents
 
- name: move prometheus bin 
  command: mv /tmp/prometheus-'{{ prom_version }}'.'{{ prom_arch }}'/prometheus '{{ bin_prom_folder }}'

- name: move promtool bin
  command: mv /tmp/prometheus-'{{ prom_version }}'.'{{ prom_arch }}'/promtool '{{ bin_prom_folder }}'

- name: mv console cfg
  command: mv  /tmp/prometheus-'{{ prom_version }}'.'{{ prom_arch }}'/consoles  '{{ conf_prom_folder }}'
  become: yes
  become_method: sudo 
  ignore_errors: yes

- name: mv console_libraries  
  command: mv  /tmp/prometheus-'{{ prom_version }}'.'{{ prom_arch }}'/console_libraries '{{ conf_prom_folder }}'
  become: yes


- name: mv prometheus.yml
  command: mv  /tmp/prometheus-'{{ prom_version }}'.'{{ prom_arch }}'/prometheus.yml '{{ conf_prom_folder }}'

- name: prometheus owner of conf folder 
  file:
    path:  '{{ conf_prom_folder }}'
    state: directory
    recurse: yes
    owner: prometheus
    group: prometheus

- name: prometheus owner of var folder 
  file:
    path:  '{{ var_prom_folder }}'
    state: directory
    recurse: yes
    owner: prometheus
    group: prometheus

- name: configure prometheus service
  template: 
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'

- name: Start service prometheus
  service:
    name: prometheus
    state: started

- name: Enable service prometheus
  service:
    name: prometheus
    enabled: yes

- name: clean package after installation
  file:
    name: '{{ item }}'
    state: absent
  with_items:
    - /tmp/prometheus-'{{ prom_version }}'.'{{ prom_arch }}'.tar.gz